endpoints:
  - path: "/"
    methods:
      - type: "GET"
        query_keys: ["foo", "bar"]
        response:
          status_code: 200
          headers:
            Content-Type: "application/json"
            Access-Control-Allow-Origin: "*"
          body: '
            {"data":
              [
                {"key": "foo", "value": "{{.foo}}"},
                {"key": "bar", "value": "{{.bar}}"}
              ]
            }
          '
      - type: "POST"
        response:
          status_code: 200
          headers:
            Content-Type: "text/plain"
          body: "ok"

  - path: "/docs"
    methods:
      - type: "GET"
        response:
          status_code: 200
          headers:
            Content-Type: "text/plain"
          body: 'hello,world'
  
