endpoints:
  - path: "/"
    methods:
      - type: "GET"
        response:
          status_code: 200
          headers:
            Content-Type: "text/plain"
            Access-Control-Allow-Origin: "*"
          body: "hello,world"
      - type: "POST"
        response:
          status_code: 200
          headers:
            Content-Type: "text/plain"
          body: "hello,world"

  - path: "/json"
    methods:
      - type: "GET"
        response:
          status_code: 200
          headers:
            Content-Type: "application/json"
          body: '{
               "glossary": {
                   "title": "example glossary",
           		"GlossDiv": {
                       "title": "S",
           			"GlossList": {
                           "GlossEntry": {
                               "ID": "SGML",
           					"SortAs": "SGML",
           					"GlossTerm": "Standard Generalized Markup Language",
           					"Acronym": "SGML",
           					"Abbrev": "ISO 8879:1986",
           					"GlossDef": {
                                   "para": "A meta-markup language, used to create markup languages such as DocBook.",
           						"GlossSeeAlso": ["GML", "XML"]
                               },
           					"GlossSee": "markup"
                           }
                       }
                   }
               }
           }'
