endpoints:
  - path: "/"
    methods:
      - type: "GET"
        queries: ["foo", "bar"]
        response:
          status_code: 200
          headers:
            Content-Type: "text/plain"
          body: "{{.foo}},{{.bar}}"
      - type: "POST"
        response:
          status_code: 201
          headers:
            Content-Type: "text/plain"
          body: "ok"
  
